stages:
  - build
  
image: maven:3-jdk-8-slim

variables:
  GIT_SUBMODULE_STRATEGY: normal
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository -DbuildTimestamp=${CI_COMMIT_TIMESTAMP} -DbuildNumber=${CI_PIPELINE_ID} -DbuildCommit=${CI_COMMIT_SHA} -DbuildUser=${GITLAB_USER_LOGIN}"  
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .m2/repository
  
build_maven:
  stage: build
  only:
  - branches
  script:
  - mvn $MAVEN_CLI_OPTS package -DskipTests -Dgenerate-pos-lib
  artifacts:
    paths:
    - comerzzia-custom-pos-application/target/*.jar
    - comerzzia-custom-pos-gui/target/lib
    expire_in: 1 hour
