stages:
  - build-artifacts
  - build-containers
  - deploy

image: maven:3-jdk-8-slim

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_IMAGE_BACKOFFICE: $DOCKER_REGISTRY_SERVER/clients/company/comerzzia/backoffice:$CI_COMMIT_REF_NAME
#  DOCKER_IMAGE_ADMIN: $DOCKER_REGISTRY_SERVER/clients/company/comerzzia/admin:$CI_COMMIT_REF_NAME
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository -DbuildTimestamp=${CI_COMMIT_TIMESTAMP} -DbuildNumber=${CI_PIPELINE_ID} -DbuildCommit=${CI_COMMIT_SHA} -DbuildUser=${GITLAB_USER_LOGIN}"  
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  K8S_WORKLOAD_BACKOFFICE: backoffice
#  K8S_WORKLOAD_ADMIN: admin
  K8S_NAMESPACE: company

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .m2/repository

build_maven:
  stage: build-artifacts
  only:
  - branches
  - tags
  script:
  - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
    - comerzzia-custom-backoffice-web/target/*.war
#    - comerzzia-custom-backoffice-admin-web/target/*.war
    expire_in: 1 hour

build_containers:
  stage: build-containers
#  when: manual  
  dependencies:
  - build_maven
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  ### create kaniko credentials file
  - cp "$KANIKO_SECRET" /kaniko/.docker/config.json

  ### backoffice build
  - echo Building image $DOCKER_IMAGE_BACKOFFICE
  - /kaniko/executor --context $CI_PROJECT_DIR/comerzzia-custom-backoffice-web/ --dockerfile $CI_PROJECT_DIR/comerzzia-custom-backoffice-web/Dockerfile --destination $DOCKER_IMAGE_BACKOFFICE
  ### backoffice admin build
#  - echo Building image $DOCKER_IMAGE_ADMIN  
#   - /kaniko/executor --context $CI_PROJECT_DIR/comerzzia-custom-backoffice-admin-web/ --dockerfile $CI_PROJECT_DIR/comerzzia-custom-backoffice-admin-web/Dockerfile --destination $DOCKER_IMAGE_ADMIN
  
### Automatic deploy to Kubernetes using Rancher
#deploy_containers:
#  stage: deploy
#  variables:
#    DOCKER_AUTH_CONFIG: "{\"auths\":{\"$TR1_REGISTRY_SERVER\":{\"auth\":\"$TR1_REGISTRY_TOKEN\"}}}"
#  only:
#  - develop
#  dependencies:
#  - build_containers
#  image: $TR1_REGISTRY_SERVER/contrib/rancher-cli-k8s
#  script:
#    - rancher login $RANCHER_SERVER --token $RANCHER_TOKEN --context $RANCHER_PROJECT
#    - rancher kubectl patch deployment $K8S_WORKLOAD_BACKOFFICE -n $K8S_NAMESPACE -p '{"spec":{"template":{"metadata":{"labels":{"date":"'`date +'%s'`'", "vcs-commit":"'$CI_COMMIT_SHA'" }}}}}'
#    - rancher kubectl patch deployment $K8S_WORKLOAD_ADMIN -n $K8S_NAMESPACE -p '{"spec":{"template":{"metadata":{"labels":{"date":"'`date +'%s'`'", "vcs-commit":"'$CI_COMMIT_SHA'" }}}}}'
